services:
  - type: web
    name: libretranslate-service
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: LT_HOST
        value: 0.0.0.0